---
- name: Install the application
  hosts: "webservers"
  gather_facts: no
  become: yes
  remote_user: azureuser
  tasks:
    - name: Install Apache from its role
      include_role:
        name: role-app
        
        
